services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - backend-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend-network
  
  gateway-api:
    image: b_gateway-api
    container_name: b_gateway
    build:
      context: .
      dockerfile: Api_Gateway/src/BApi_Gateway/BApi_Gateway/Dockerfile
    ports:
      - "8100:8080"
    networks:
      - backend-network
    environment:
      - JWT_SECRET_KEY=BShp_Gtwy_Secr_Key_2026_BWAR_32_!

  # --- User service ---
  user-api:
    image: buser-api
    container_name: buser-api
    build:
      context: .
      dockerfile: Services/BilTech_User/src/BUser.Api/Dockerfile
    environment:
      - ConnectionStrings__DbUserContext=Host=user-db;Port=5432;Database=UserDb;Username=postgres;Password=123456
      - JWT_SECRET_KEY=BShp_Gtwy_Secr_Key_2026_BWAR_32_!
    depends_on:
      - user-db
    ports:
      - "8001:8080"
    networks:
      - backend-network

  # --- User database ---
  user-db:
    image: postgres:17-alpine
    container_name: buser-user-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: UserDb
    ports:
      - "5433:5432"
    volumes:
      - buser_db-data:/var/lib/postgresql/data
    networks:
      - backend-network

  # --- Shop service ---
  shop-api:
    image: bshop-shop-api
    container_name: bshop-api
    build:
      context: .
      dockerfile: Services/BilTech_Shop/src/BShop.Api/Dockerfile
    environment:
      - ConnectionStrings__ShopDbContext=Host=shop-db;Port=5432;Database=ShopDb;Username=postgres;Password=123456
      - JWT_SECRET_KEY=BShp_Gtwy_Secr_Key_2026_BWAR_32_!
    depends_on:
      - kafka
      - shop-db
    ports:
      - "8000:8080"
    networks:
      - backend-network
  
  # --- Shop database ---
  shop-db:
    image: postgres:17-alpine
    container_name: bshop-shop-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ShopDb
    volumes:
      - bshop_db-data:/var/lib/postgresql/data
    networks:
      - backend-network
  
  # --- Warehouse Database ---
  warehouse-db:
    image: postgres:latest
    container_name: warehouse_db
    environment:
      POSTGRES_DB: WarehouseDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    networks:
      - backend-network

  # --- Warehouse Service ---
  warehouse-api:
    image: warehouse-api
    container_name: warehouse_api
    build:
      context: .
      dockerfile: Services/BilTech_Warehouse/src/Warehouse.Api/Warehouse.Api/Dockerfile
    depends_on:
      - warehouse-db
      - kafka
    networks:
      - backend-network
    environment:
      - ConnectionStrings__DefaultConnection=Host=warehouse-db;Database=WarehouseDb;Username=postgres;Password=postgres
      - JWT_SECRET_KEY=BShp_Gtwy_Secr_Key_2026_BWAR_32_!

networks:
  backend-network:
    driver: bridge

volumes:
  bshop_db-data:
  buser_db-data: