<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\BUser.Api\BUser.Api.csproj" />
      <ProjectReference Include="..\BUser.Domain\BUser.Domain.csproj" />
      <ProjectReference Include="..\BUser.Infrastructure\BUser.Infrastructure.csproj" />
    </ItemGroup>

</Project>
